settings:
  title: 'MysteryQuest'
  url: 'https://questionnaire-status.jaap.su' # used for Slack messages
  logo: index.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Alle systemen operationeel'
  notAllmonitorsOperational: 'Niet alle systemen operationeel'
  monitorLabelOperational: 'Operationeel'
  monitorLabelNotOperational: 'Niet Operationeel'
  monitorLabelNoData: 'Geen data'
  dayInHistogramNoData: 'Geen data'
  dayInHistogramOperational: 'Alles goed'
  dayInHistogramNotOperational: ' incident(en)' # xx incident(s) recorded

monitors:
  - id: questionnaire-portal-dev # unique identifier
    name: 'MysteryQuest Developer Portaal'
    description: 'MysteryQuest Developer Portaal' # default=empty
    url: 'https://questionnaire-dev.jaap.su/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: questionnaire-portal-acc
    name: 'MysteryQuest Acceptatie Portaal'
    description: 'MysteryQuest Acceptatie Portaal'
    url: 'https://questionnaire-acc.jaap.su/login'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true # allows the title to be a link, default=true
