settings:
  title: 'MysteryQuest'
  url: 'https://questionnaire-status.jaap.su' # used for Slack messages
  logo: index.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'Geen data'
  dayInHistogramNoData: 'Geen data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: questionnaire-portal-dev # unique identifier
    name: questionnaire-dev.jaap.su
    description: 'MysteryQuest Developer Portaal' # default=empty
    url: 'https://questionnaire-dev.jaap.su' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: questionnaire-portal-acc
    name: questionnaire-acc.jaap.su
    description: 'MysteryQuest Acceptatie Portaal'
    url: 'https://questionnaire-acc.jaap.su'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true # allows the title to be a link, default=true
